development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: drmat_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://drmat_redis:6379/1
  channel_prefix: drmat_production
